// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG9_lixqdx1aFi3o2YrSJLwuAURRBW2vU',
    appId: '1:708077956449:android:56c2be385806c348726920',
    messagingSenderId: '708077956449',
    projectId: 'lightcutoff-dev',
    databaseURL: 'https://lightcutoff-dev.firebaseio.com',
    storageBucket: 'lightcutoff-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAng1bLMh3gMCjmsB8ccbI3YuBDeAQVoUk',
    appId: '1:708077956449:ios:cf24083083a70353726920',
    messagingSenderId: '708077956449',
    projectId: 'lightcutoff-dev',
    databaseURL: 'https://lightcutoff-dev.firebaseio.com',
    storageBucket: 'lightcutoff-dev.appspot.com',
    iosClientId:
        '708077956449-27cueb3t4dphkp3p8gsuqfc653vbgbg9.apps.googleusercontent.com',
    iosBundleId: 'com.njuka.app',
  );
}
